name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: vgaidarji/android-github-actions/build@v1.0.0
    - name: Build with Gradle
      run: ./gradlew build
